<a href="https://colab.research.google.com/github/nafl13/ICT_Internship/blob/day2/D2_numpy_and_pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
list1=[1,2,3,4]
list2=[5,6,7,8]

In [ ]:
sum=list1+list2
sum

[1, 2, 3, 4, 5, 6, 7, 8]

In [ ]:
sum_1=[]
for num1,num2,in zip(list1,list2):
  sum_1.append(num1+num2)
sum_1

[6, 8, 10, 12]

In [2]:
import numpy as np
import pandas as pd

In [ ]:
arr1=np.array(list1)
arr1
arr2=np.array(list2)
sum_l1=arr1+arr2
sum_l1

array([ 6,  8, 10, 12])

In [ ]:
arr1.ndim
#or np.ndim(arr1)

1

In [ ]:
list3=[[2,3,4],[5,6,8]]
list3

[[2, 3, 4], [5, 6, 8]]

In [ ]:
arr3=np.array(list3)
arr3
#arr3.ndim

array([[2, 3, 4],
       [5, 6, 8]])

In [ ]:
arr3.shape


(2, 3)

In [ ]:
arr4=np.arange(6)
arr4

array([0, 1, 2, 3, 4, 5])

In [ ]:
arr5=arr4.reshape(2,3)
arr5

array([[0, 1, 2],
       [3, 4, 5]])

In [ ]:
arr4.mean()

2.5

In [ ]:
np.sqrt(arr5)

array([[0.        , 1.        , 1.41421356],
       [1.73205081, 2.        , 2.23606798]])

In [ ]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
np.random.rand(3,4)

array([[0.50994547, 0.15714813, 0.17161285, 0.86358664],
       [0.7957396 , 0.52748401, 0.08144709, 0.48632321],
       [0.43311597, 0.43342969, 0.16642587, 0.02279314]])

In [7]:
data=pd.read_csv('/content/Dataset/auto-mpg.csv')
data

mpg  cylinders  displacement horsepower  weight  acceleration  \
0    18.0          8         307.0        130    3504          12.0   
1    15.0          8         350.0        165    3693          11.5   
2    18.0          8         318.0        150    3436          11.0   
3    16.0          8         304.0        150    3433          12.0   
4    17.0          8         302.0        140    3449          10.5   
..    ...        ...           ...        ...     ...           ...   
393  27.0          4         140.0         86    2790          15.6   
394  44.0          4          97.0         52    2130          24.6   
395  32.0          4         135.0         84    2295          11.6   
396  28.0          4         120.0         79    2625          18.6   
397  31.0          4         119.0         82    2720          19.4   

     model year  origin                   car name  
0            70       1  chevrolet chevelle malibu  
1            70       1          buick skylark 320  
2            70       1         plymouth satellite  
3            70       1              amc rebel sst  
4            70       1                ford torino  
..          ...     ...                        ...  
393          82       1            ford mustang gl  
394          82       2                  vw pickup  
395          82       1              dodge rampage  
396          82       1                ford ranger  
397          82       1                 chevy s-10  

[398 rows x 9 columns]